<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Apache.Arrow" Version="23.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.7" />
  </ItemGroup>
</Project>
